import { useState, useEffect } from "react";
import {
  BrainCircuit,
  RefreshCw,
  Sparkles,
  AlertTriangle,
  CheckCircle2,
  ShieldAlert,
  Clock,
  Hospital,
  TrendingUp,
} from "lucide-react";
import forecastService from "../../services/forecastService";
import {
  DEMO_HIGH_RISK_ITEMS,
  DEMO_RISK_DISTRIBUTION,
  DEMO_RISK_BY_HOSPITAL,
} from "./demoForecastData";

/**
 * ForecastNarrative — AI-generated executive summary panel.
 *
 * Shows a Gemini-generated or rule-based narrative about current forecast status.
 * Uses structured card layout with risk badges instead of raw text.
 */
export default function ForecastNarrative() {
  const [narrative, setNarrative] = useState(null);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [source, setSource] = useState(null);

  const fetchNarrative = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await forecastService.getNarrative();
      if (result.success) {
        setNarrative(result.narrative);
        setStats(result.stats);
        setSource(result.source);
      } else {
        setError(result.error || "Failed to generate narrative");
        applyDemoFallback();
      }
    } catch {
      setError("Unable to connect to forecast API");
      applyDemoFallback();
    } finally {
      setLoading(false);
    }
  };

  const applyDemoFallback = () => {
    setSource("demo");
    setStats({ risk_distribution: DEMO_RISK_DISTRIBUTION });
    setNarrative(null);
  };

  useEffect(() => {
    fetchNarrative();
  }, []);

  if (loading) {
    return (
      <div className="bg-white rounded-xl border border-gray-200 p-6 animate-pulse">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-purple-100 rounded-lg" />
          <div className="h-5 bg-gray-200 rounded w-48" />
        </div>
        <div className="space-y-2">
          <div className="h-4 bg-gray-200 rounded w-full" />
          <div className="h-4 bg-gray-200 rounded w-5/6" />
          <div className="h-4 bg-gray-200 rounded w-4/6" />
        </div>
      </div>
    );
  }

  const riskDist = stats?.risk_distribution || {};
  const criticalCount = (riskDist.critical || 0) + (riskDist.high || 0);
  const isHealthy = criticalCount === 0;
  const isDemo = source === "demo";

  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 bg-gradient-to-r from-purple-50 to-indigo-50">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-purple-100 rounded-lg">
            <BrainCircuit className="w-5 h-5 text-purple-600" />
          </div>
          <div>
            <h3 className="font-semibold text-gray-900">AI Executive Summary</h3>
            <p className="text-xs text-gray-500 flex items-center gap-1">
              {source === "gemini" && (
                <Sparkles className="w-3 h-3 text-purple-500" />
              )}
              {source === "gemini"
                ? "Generated by Gemini AI"
                : source === "rule_based"
                ? "Rule-based analysis"
                : "Demo data"}
              <span className="text-gray-300 mx-1">•</span>
              {new Date().toLocaleDateString("en-PH", {
                month: "short",
                day: "numeric",
                hour: "2-digit",
                minute: "2-digit",
              })}
            </p>
          </div>
        </div>
        <button
          onClick={fetchNarrative}
          className="p-2 text-gray-400 hover:text-purple-600 hover:bg-purple-50 rounded-lg transition-colors"
          title="Refresh narrative"
        >
          <RefreshCw className="w-4 h-4" />
        </button>
      </div>

      {/* Status Banner */}
      {!isHealthy ? (
        <div className="px-5 py-2.5 bg-red-50 border-b border-red-100 flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0" />
          <span className="text-sm font-medium text-red-800">
            {criticalCount.toLocaleString()} predictions flagged as high or
            critical risk — immediate action recommended
          </span>
        </div>
      ) : (
        <div className="px-5 py-2.5 bg-green-50 border-b border-green-100 flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0" />
          <span className="text-sm font-medium text-green-800">
            All supply levels within safe thresholds
          </span>
        </div>
      )}

      {/* Body */}
      <div className="p-5 space-y-4">
        {error && (
          <p className="text-xs text-amber-600 mb-1 flex items-center gap-1">
            <AlertTriangle className="w-3 h-3" />
            {error} — showing fallback data
          </p>
        )}

        {narrative && !isDemo ? (
          <RawNarrativeDisplay narrative={narrative} />
        ) : (
          <StructuredNarrative />
        )}
      </div>

      {/* Stats Footer */}
      {riskDist && Object.keys(riskDist).length > 0 && (
        <div className="px-5 py-3 bg-gray-50 border-t border-gray-100 grid grid-cols-4 gap-4">
          <StatBadge label="Low" count={riskDist.low || 0} color="green" />
          <StatBadge label="Medium" count={riskDist.medium || 0} color="yellow" />
          <StatBadge label="High" count={riskDist.high || 0} color="orange" />
          <StatBadge
            label="Critical"
            count={riskDist.critical || 0}
            color="red"
          />
        </div>
      )}
    </div>
  );
}

/* ───────────────────────── Structured Demo Narrative ────────────────────── */
function StructuredNarrative() {
  const topItems = DEMO_HIGH_RISK_ITEMS.slice(0, 5);
  const hospitals = DEMO_RISK_BY_HOSPITAL;

  return (
    <div className="space-y-4">
      {/* Alert Box */}
      <div className="flex items-start gap-3 p-3 bg-red-50 border border-red-200 rounded-lg">
        <ShieldAlert className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-semibold text-red-800">
            Multiple hospitals with critically low supply levels detected
          </p>
          <p className="text-xs text-red-600 mt-0.5">
            Immediate action recommended for blood products and emergency
            supplies across Metro Manila.
          </p>
        </div>
      </div>

      {/* Priority Items */}
      <div>
        <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
          <TrendingUp className="w-3.5 h-3.5" />
          Priority Items
        </h4>
        <div className="space-y-2">
          {topItems.map((item, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between px-3 py-2 rounded-lg border border-gray-100 hover:bg-gray-50 transition-colors"
            >
              <div className="flex items-center gap-3 min-w-0">
                <span className="text-xs font-bold text-gray-400 w-5 text-right flex-shrink-0">
                  {idx + 1}.
                </span>
                <div className="min-w-0">
                  <p className="text-sm font-medium text-gray-800 truncate">
                    {item.hospital.name}
                  </p>
                  <p className="text-xs text-gray-500 truncate">
                    {item.resource.name}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0 ml-3">
                <RiskBadge level={item.risk_level} prob={item.risk_prob} />
                <div className="text-right">
                  <p className="text-xs font-semibold text-amber-700 flex items-center gap-0.5">
                    <Clock className="w-3 h-3" />
                    {item.days_until_stockout < 1
                      ? "< 1 day"
                      : `~${item.days_until_stockout.toFixed(1)}d`}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Hospital Attention */}
      <div>
        <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
          <Hospital className="w-3.5 h-3.5" />
          Hospitals Requiring Attention
        </h4>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          {hospitals.map((h, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between px-3 py-2 bg-orange-50 rounded-lg border border-orange-100"
            >
              <span className="text-sm text-gray-800 font-medium truncate">
                {h.name}
              </span>
              <span className="text-xs font-bold text-orange-700 ml-2 flex-shrink-0">
                {h.risk_count} at-risk
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Risk Posture */}
      <div className="flex items-center gap-2 p-3 bg-amber-50 border border-amber-200 rounded-lg">
        <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0" />
        <p className="text-sm text-amber-800">
          <span className="font-semibold">Overall Risk Posture: ELEVATED.</span>{" "}
          Proactive reorder requests have been automatically generated for the
          highest-priority items.
        </p>
      </div>
    </div>
  );
}

/* ────────────── Raw Narrative (API response) ─────────────── */
function RawNarrativeDisplay({ narrative }) {
  const lines = narrative.split("\n").filter((l) => l.trim());
  const sections = [];
  let currentSection = { title: "", items: [] };

  lines.forEach((line) => {
    const trimmed = line.trim();
    if (
      (trimmed === trimmed.toUpperCase() && trimmed.length > 5 && !trimmed.startsWith("•") && !trimmed.match(/^\d/)) ||
      trimmed.match(/^[A-Z\s]+:$/)
    ) {
      if (currentSection.title || currentSection.items.length) {
        sections.push({ ...currentSection });
      }
      currentSection = { title: trimmed.replace(/:$/, ""), items: [] };
    } else {
      currentSection.items.push(trimmed);
    }
  });
  if (currentSection.title || currentSection.items.length) {
    sections.push(currentSection);
  }

  return (
    <div className="space-y-3">
      {sections.map((section, idx) => (
        <div key={idx}>
          {section.title && (
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
              {section.title}
            </h4>
          )}
          <div className="space-y-1">
            {section.items.map((item, i) => {
              const isAlert = item.includes("⚠") || item.toLowerCase().includes("alert");
              const isBullet = item.startsWith("•") || item.startsWith("-") || item.match(/^\d+\./);
              return (
                <p
                  key={i}
                  className={`text-sm leading-relaxed ${
                    isAlert
                      ? "text-red-700 font-medium bg-red-50 px-3 py-1.5 rounded-lg border border-red-100"
                      : isBullet
                      ? "text-gray-700 pl-3"
                      : "text-gray-700"
                  }`}
                >
                  {item}
                </p>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

/* ──────────────────── Shared Sub-components ──────────────── */
function RiskBadge({ level, prob }) {
  const colors = {
    critical: "bg-red-100 text-red-800 border-red-200",
    high: "bg-orange-100 text-orange-800 border-orange-200",
    medium: "bg-yellow-100 text-yellow-800 border-yellow-200",
    low: "bg-green-100 text-green-800 border-green-200",
  };
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-bold border ${
        colors[level] || colors.medium
      }`}
    >
      {Math.round(prob * 100)}%
    </span>
  );
}

function StatBadge({ label, count, color }) {
  const colorMap = {
    green: "bg-green-100 text-green-800",
    yellow: "bg-yellow-100 text-yellow-800",
    orange: "bg-orange-100 text-orange-800",
    red: "bg-red-100 text-red-800",
  };
  return (
    <div className="text-center">
      <div
        className={`inline-block px-2 py-0.5 rounded-full text-xs font-semibold ${colorMap[color]}`}
      >
        {count.toLocaleString()}
      </div>
      <p className="text-xs text-gray-500 mt-0.5">{label}</p>
    </div>
  );
}
