<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patient Care Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 9pt; color: #000; margin: 0; padding: 8px; }
        h1 { text-align: center; margin: 0 0 8px 0; font-size: 14pt; }
        .meta { margin-bottom: 6px; font-size: 8.5pt; }
        .section { border: 1px solid #000; margin-bottom: 6px; page-break-inside: avoid; }
        .section-title { background: #f1f1f1; border-bottom: 1px solid #000; padding: 2px 4px; font-weight: 700; font-size: 8.5pt; }
        .grid { width: 100%; border-collapse: collapse; font-size: 8.5pt; }
        .grid td, .grid th { border: 1px solid #000; padding: 2px; vertical-align: top; }
        .compact-table td, .compact-table th { padding: 2px 3px; }
        .text-xxs { font-size: 7.5pt; line-height: 1.1; }
        .flow-row { display: flex; gap: 4px; }
        .flow-col { width: 50%; }
        .chip-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 4px; }
        .chip { border: 1px solid #000; border-radius: 4px; padding: 2px 4px; }
        .footer-meta { margin-top: 4px; font-size: 7.5pt; }
        .signature-box { min-height: 36px; padding: 4px; }
        .no-break { page-break-inside: avoid; }
    </style>
</head>
<body>
    <h1>MDRRMO PATIENT CARE REPORT</h1>

    <div class="meta">
        <strong>Case No:</strong> {{ $report->case_no ?? 'N/A' }} |
        <strong>Unit:</strong> {{ $report->mobile_unit ?? 'N/A' }} |
        <strong>Date:</strong> {{ optional($report->dispatch_date)->format('Y-m-d') ?? 'N/A' }}
        <span class="footer-meta">Generated By: {{ $generatedBy ?? 'System' }}</span>
    </div>

    <div class="section">
        <div class="section-title">Dispatch Info</div>
        <table class="grid">
            <tr>
                <td><strong>Dispatch</strong><br>{{ data_get($report->response_times, 'dispatch', 'N/A') }}</td>
                <td><strong>Arrival</strong><br>{{ data_get($report->response_times, 'arrival', 'N/A') }}</td>
                <td><strong>Back to Base</strong><br>{{ data_get($report->response_times, 'back_to_base', 'N/A') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Patient Details</div>
        <table class="grid">
            <tr>
                <td><strong>Name</strong><br>{{ data_get($report->patient_details, 'name', 'N/A') }}</td>
                <td><strong>Age</strong><br>{{ data_get($report->patient_details, 'age', 'N/A') }}</td>
                <td><strong>Gender</strong><br>{{ data_get($report->patient_details, 'gender', 'N/A') }}</td>
            </tr>
            <tr>
                <td colspan="2"><strong>Address</strong><br>{{ data_get($report->patient_details, 'address', 'N/A') }}</td>
                <td><strong>Emergency Contact</strong><br>{{ data_get($report->patient_details, 'emergencyContact', 'N/A') }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">NOI / MOI / PMH</div>
        <div class="flow-row text-xxs">
            <div class="flow-col">
                <strong>NOI / MOI</strong>
                <div class="chip-grid">
                    @foreach((array) data_get($report, 'noi_moi', []) as $item)
                        <div class="chip">{{ $item }}</div>
                    @endforeach
                    @if(empty(data_get($report, 'noi_moi')))
                        <div class="chip">N/A</div>
                    @endif
                </div>
            </div>
            <div class="flow-col">
                <strong>Past Medical History</strong>
                <div class="chip-grid">
                    @foreach((array) data_get($report, 'physiological_status.pmh', []) as $item)
                        <div class="chip">{{ $item }}</div>
                    @endforeach
                    @if(empty(data_get($report, 'physiological_status.pmh')))
                        <div class="chip">N/A</div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="section no-break">
        <div class="section-title">Vitals and GCS</div>
        <table class="grid compact-table">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>BP</th>
                    <th>Temp</th>
                    <th>RR</th>
                    <th>SpO2</th>
                    <th>Pulse</th>
                    <th>GCS</th>
                    <th>Source</th>
                </tr>
            </thead>
            <tbody>
            @forelse($report->vitals as $vital)
                <tr>
                    <td>{{ $vital->recorded_time ?: 'N/A' }}</td>
                    <td>{{ $vital->blood_pressure ?: 'N/A' }}</td>
                    <td>{{ $vital->temperature ?: 'N/A' }}</td>
                    <td>{{ $vital->respiratory_rate ?: 'N/A' }}</td>
                    <td>{{ $vital->spo2 ?: 'N/A' }}</td>
                    <td>{{ $vital->pulse ?: 'N/A' }}</td>
                    <td>{{ $vital->gcs_eyes ?: '-' }}/{{ $vital->gcs_verbal ?: '-' }}/{{ $vital->gcs_motor ?: '-' }}<br><strong>{{ $vital->gcs_total ?: '-' }}</strong></td>
                    <td>{{ strtoupper($vital->source ?? 'manual') }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No vitals recorded.</td></tr>
            @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Management and Transport</div>
        <table class="grid compact-table">
            <tr>
                <td><strong>Treatment Narrative</strong><br>{{ data_get($report->management_transport, 'treatmentNarrative', 'N/A') }}</td>
            </tr>
            <tr>
                <td><strong>Transported To</strong><br>{{ data_get($report->management_transport, 'transportedTo', 'N/A') }}</td>
            </tr>
            <tr>
                <td><strong>Admitting Doctor</strong><br>{{ data_get($report->management_transport, 'admittingDoctor', 'N/A') }}</td>
            </tr>
            <tr>
                <td><strong>Personnel on Scene</strong><br>{{ is_array(data_get($report->management_transport, 'personnelOnScene')) ? implode(', ', data_get($report->management_transport, 'personnelOnScene')) : (data_get($report->management_transport, 'personnelOnScene', 'N/A')) }}</td>
            </tr>
        </table>
    </div>

    <div class="section no-break">
        <div class="section-title">Waivers</div>
        <table class="grid compact-table">
            <tr>
                <td>Consent for Treatment:<br>{{ $report->waiver?->consent_for_treatment ? 'YES' : 'NO' }}</td>
                <td>Refusal of Treatment:<br>{{ $report->waiver?->refusal_of_treatment ? 'YES' : 'NO' }}</td>
                <td>Equipment Liability:<br>{{ $report->waiver?->equipment_liability_agreement ? 'YES' : 'NO' }}</td>
            </tr>
            <tr>
                <td colspan="3"><strong>Signer</strong><br>{{ $report->waiver?->signer_name ?? data_get($report->waivers, 'signerName', 'N/A') }}</td>
            </tr>
            <tr>
                <td colspan="3"><strong>Consent Signature</strong><br>{{ $report->waiver?->consent_signature_path ? 'SIGNED' : 'None' }}</td>
            </tr>
            <tr>
                <td colspan="3"><strong>Refusal Signature</strong><br>{{ $report->waiver?->refusal_signature_path ? 'SIGNED' : 'None' }}</td>
            </tr>
            <tr>
                <td colspan="3"><strong>Equipment Signature</strong><br>{{ $report->waiver?->equipment_signature_path ? 'SIGNED' : 'None' }}</td>
            </tr>
        </table>
    </div>
</body>
</html>
