<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Epic 4 — Anomaly-Triggered Intraday Recalculation
 *
 * Stores anomaly alerts generated by IntradayAnomalyService when
 * real-time consumption exceeds the forecasted depletion curve by
 * more than 1.5 standard deviations.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('anomaly_alerts', function (Blueprint $table) {
            $table->id();

            $table->unsignedBigInteger('hospital_id');
            $table->unsignedBigInteger('resource_id');
            $table->timestamp('detected_at')->index();

            // Z-score stats
            $table->float('z_score');
            $table->float('actual_consumption');
            $table->float('expected_consumption');
            $table->float('historical_std');

            // Classification
            $table->string('severity', 10)->default('warning')
                  ->comment('normal | warning | critical');
            $table->text('details')->nullable();

            // Resolution tracking
            $table->boolean('resolved')->default(false);
            $table->timestamp('resolved_at')->nullable();
            $table->unsignedBigInteger('resolved_by')->nullable()
                  ->comment('user_id who acknowledged');

            $table->timestamps();

            // Indexes for dashboard queries
            $table->index(['hospital_id', 'detected_at']);
            $table->index(['severity', 'resolved']);
            $table->foreign('hospital_id')->references('id')->on('hospitals')->cascadeOnDelete();
            $table->foreign('resource_id')->references('id')->on('resources')->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('anomaly_alerts');
    }
};
