<?php

namespace Database\Seeders;

use App\Models\Hospital;
use Illuminate\Database\Seeder;

class HospitalSeeder extends Seeder
{
    public function run(): void
    {
        Hospital::truncate();

        $hospitals = [
            [
                'name'                  => 'Northern Tagalog Regional Hospital (NTRH)',
                'code'                  => 'RIZ-NTRH-001',
                'short_name'            => 'NTRH',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Rodriguez (Montalban)',
                'address'               => 'Brgy. San Jose, Rodriguez (Montalban), Rizal',
                'phone'                 => '0288001001',
                'email'                 => 'ntrh@kalinga.com',
                'director_name'         => 'Dr. NTRH Director',
                'capacity'              => 420,
                'bed_capacity'          => 420,
                'icu_capacity'          => 42,
                'negative_pressure_rooms' => 12,
                'level'                 => 'Level 3',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.7524831,
                'longitude'             => 121.1324890,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Rizal Medical Center (RMC)',
                'code'                  => 'NCR-RMC-001',
                'short_name'            => 'RMC',
                'region'                => 'NCR',
                'province'              => 'Metro Manila',
                'city_municipality'     => 'Pasig City',
                'address'               => '425 Pasig Boulevard, Bagong Ilog, Pasig City, Metro Manila',
                'phone'                 => '0288001002',
                'email'                 => 'rmc@kalinga.com',
                'director_name'         => 'Dr. RMC Director',
                'capacity'              => 500,
                'bed_capacity'          => 500,
                'icu_capacity'          => 55,
                'negative_pressure_rooms' => 16,
                'level'                 => 'Level 3',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.5633241,
                'longitude'             => 121.0660277,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Angono General Hospital',
                'code'                  => 'RIZ-ANG-001',
                'short_name'            => 'Angono General',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Angono',
                'address'               => 'Manila East Road, Brgy. San Isidro, Angono, Rizal',
                'phone'                 => '0288001003',
                'email'                 => 'angono.general@kalinga.com',
                'director_name'         => 'Dr. Angono Director',
                'capacity'              => 180,
                'bed_capacity'          => 180,
                'icu_capacity'          => 18,
                'negative_pressure_rooms' => 4,
                'level'                 => 'Level 2',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.5268124,
                'longitude'             => 121.1520970,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Rizal Provincial Hospital System (RPHS) - Morong (Main)',
                'code'                  => 'RIZ-RPHS-MOR-001',
                'short_name'            => 'RPHS Morong',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Morong',
                'address'               => 'Tomas Claudio St., San Juan, Morong, Rizal',
                'phone'                 => '0288001004',
                'email'                 => 'rphs.morong@kalinga.com',
                'director_name'         => 'Dr. RPHS Morong Director',
                'capacity'              => 260,
                'bed_capacity'          => 260,
                'icu_capacity'          => 20,
                'negative_pressure_rooms' => 5,
                'level'                 => 'Level 2',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.5166549,
                'longitude'             => 121.2393856,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'RPHS - Antipolo Annex I',
                'code'                  => 'RIZ-RPHS-ANT1-001',
                'short_name'            => 'RPHS Antipolo I',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Antipolo',
                'address'               => 'Brgy. Dela Paz, Antipolo, Rizal',
                'phone'                 => '0288001005',
                'email'                 => 'rphs.antipolo1@kalinga.com',
                'director_name'         => 'Dr. RPHS Antipolo I Director',
                'capacity'              => 120,
                'bed_capacity'          => 120,
                'icu_capacity'          => 8,
                'negative_pressure_rooms' => 2,
                'level'                 => 'Level 1',
                'ownership'             => 'government',
                'type'                  => 'Emergency',
                'latitude'              => 14.6196771,
                'longitude'             => 121.1803323,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> false,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'RPHS - Antipolo Annex II',
                'code'                  => 'RIZ-RPHS-ANT2-001',
                'short_name'            => 'RPHS Antipolo II',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Antipolo',
                'address'               => 'Brgy. Dalig, Antipolo, Rizal',
                'phone'                 => '0288001006',
                'email'                 => 'rphs.antipolo2@kalinga.com',
                'director_name'         => 'Dr. RPHS Antipolo II Director',
                'capacity'              => 130,
                'bed_capacity'          => 130,
                'icu_capacity'          => 10,
                'negative_pressure_rooms' => 2,
                'level'                 => 'Level 1',
                'ownership'             => 'government',
                'type'                  => 'Emergency',
                'latitude'              => 14.5782488,
                'longitude'             => 121.1860463,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> false,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'RPHS - Antipolo Annex III',
                'code'                  => 'RIZ-RPHS-ANT3-001',
                'short_name'            => 'RPHS Antipolo III',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Antipolo',
                'address'               => 'Sitio Cabading, Brgy. Inarawan, Antipolo, Rizal',
                'phone'                 => '0288001007',
                'email'                 => 'rphs.antipolo3@kalinga.com',
                'director_name'         => 'Dr. RPHS Antipolo III Director',
                'capacity'              => 90,
                'bed_capacity'          => 90,
                'icu_capacity'          => 6,
                'negative_pressure_rooms' => 1,
                'level'                 => 'Level 1',
                'ownership'             => 'government',
                'type'                  => 'Emergency',
                'latitude'              => 14.6341271,
                'longitude'             => 121.2286184,
                'is_active'             => true,
                'is_cold_chain_capable' => false,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => false,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> false,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'RPHS - Binangonan Annex',
                'code'                  => 'RIZ-RPHS-BIN-001',
                'short_name'            => 'RPHS Binangonan',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Binangonan',
                'address'               => 'Manila East Road, Brgy. Darangan, Binangonan, Rizal',
                'phone'                 => '0288001008',
                'email'                 => 'rphs.binangonan@kalinga.com',
                'director_name'         => 'Dr. RPHS Binangonan Director',
                'capacity'              => 150,
                'bed_capacity'          => 150,
                'icu_capacity'          => 12,
                'negative_pressure_rooms' => 3,
                'level'                 => 'Level 1',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.4891464,
                'longitude'             => 121.1864085,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'RPHS - Casimiro A. Ynares, Sr. Memorial Hospital',
                'code'                  => 'RIZ-RPHS-CAY-001',
                'short_name'            => 'RPHS CAY Memorial',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Rodriguez (Montalban)',
                'address'               => 'Highway, Brgy. San Jose, Rodriguez (Montalban), Rizal',
                'phone'                 => '0288001009',
                'email'                 => 'rphs.cay@kalinga.com',
                'director_name'         => 'Dr. CAY Memorial Director',
                'capacity'              => 200,
                'bed_capacity'          => 200,
                'icu_capacity'          => 16,
                'negative_pressure_rooms' => 4,
                'level'                 => 'Level 2',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.7143644,
                'longitude'             => 121.1346161,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'RPHS - Tanay Annex',
                'code'                  => 'RIZ-RPHS-TAN-001',
                'short_name'            => 'RPHS Tanay',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Tanay',
                'address'               => 'Tanay, Rizal',
                'phone'                 => '0288001010',
                'email'                 => 'rphs.tanay@kalinga.com',
                'director_name'         => 'Dr. RPHS Tanay Director',
                'capacity'              => 140,
                'bed_capacity'          => 140,
                'icu_capacity'          => 10,
                'negative_pressure_rooms' => 2,
                'level'                 => 'Level 1',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.5128275,
                'longitude'             => 121.2848965,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Montalban Municipal Health Center',
                'code'                  => 'RIZ-MONTALBAN-MHC-001',
                'short_name'            => 'Montalban MHC',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Rodriguez (Montalban)',
                'address'               => '139 J. P. Rizal St, Rodriguez, Calabarzon',
                'phone'                 => '0288001012',
                'email'                 => 'montalban.mhc@kalinga.com',
                'director_name'         => 'Dr. Montalban MHC Director',
                'capacity'              => 80,
                'bed_capacity'          => 80,
                'icu_capacity'          => 4,
                'negative_pressure_rooms' => 1,
                'level'                 => 'Level 1',
                'ownership'             => 'government',
                'type'                  => 'Emergency',
                'latitude'              => 14.7333809,
                'longitude'             => 121.1452632,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> false,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'H Vill Hospital',
                'code'                  => 'RIZ-HVILL-001',
                'short_name'            => 'H Vill',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Rodriguez (Montalban)',
                'address'               => 'P4GV+M5G, J. P. Rizal St, Rodriguez, 1860 Rizal',
                'phone'                 => '0288001013',
                'email'                 => 'hvill@kalinga.com',
                'director_name'         => 'Dr. H Vill Director',
                'capacity'              => 110,
                'bed_capacity'          => 110,
                'icu_capacity'          => 8,
                'negative_pressure_rooms' => 2,
                'level'                 => 'Level 1',
                'ownership'             => 'private',
                'type'                  => 'General',
                'latitude'              => 14.7268572,
                'longitude'             => 121.1429308,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'N. Med Care Hospital',
                'code'                  => 'RIZ-NMEDCARE-001',
                'short_name'            => 'N. Med Care',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'Rodriguez (Montalban)',
                'address'               => '143 A Mabini St, Rodriguez, 1860 Rizal',
                'phone'                 => '0288001014',
                'email'                 => 'nmedcare@kalinga.com',
                'director_name'         => 'Dr. N. Med Care Director',
                'capacity'              => 95,
                'bed_capacity'          => 95,
                'icu_capacity'          => 6,
                'negative_pressure_rooms' => 1,
                'level'                 => 'Level 1',
                'ownership'             => 'private',
                'type'                  => 'General',
                'latitude'              => 14.7231731,
                'longitude'             => 121.1413244,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Rosario Maclang Bautista General Hospital',
                'code'                  => 'NCR-RMBGH-001',
                'short_name'            => 'RMBGH',
                'region'                => 'NCR',
                'province'              => 'Metro Manila',
                'city_municipality'     => 'Quezon City',
                'address'               => 'M3PQ+CJG, Batasan Rd, Quezon City, Metro Manila',
                'phone'                 => '0288001015',
                'email'                 => 'rmbgh@kalinga.com',
                'director_name'         => 'Dr. RMBGH Director',
                'capacity'              => 220,
                'bed_capacity'          => 220,
                'icu_capacity'          => 20,
                'negative_pressure_rooms' => 5,
                'level'                 => 'Level 2',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.6871899,
                'longitude'             => 121.0888400,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'San Mateo Medical Center',
                'code'                  => 'RIZ-SMMC-001',
                'short_name'            => 'SMMC',
                'region'                => 'Region IV-A',
                'province'              => 'Rizal',
                'city_municipality'     => 'San Mateo',
                'address'               => '156 Gen. Luna Ave, Ampid 2, San Mateo, 1850 Rizal',
                'phone'                 => '0288001016',
                'email'                 => 'smmc@kalinga.com',
                'director_name'         => 'Dr. SMMC Director',
                'capacity'              => 210,
                'bed_capacity'          => 210,
                'icu_capacity'          => 18,
                'negative_pressure_rooms' => 5,
                'level'                 => 'Level 2',
                'ownership'             => 'private',
                'type'                  => 'General',
                'latitude'              => 14.6863885,
                'longitude'             => 121.1158419,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'San Lorenzo Hospital',
                'code'                  => 'NCR-SLH-001',
                'short_name'            => 'San Lorenzo',
                'region'                => 'NCR',
                'province'              => 'Metro Manila',
                'city_municipality'     => 'Quezon City',
                'address'               => 'P2JW+7CR, 1118 Quirino Hwy, Novaliches, Quezon City, 1118 Metro Manila',
                'phone'                 => '0288001017',
                'email'                 => 'sanlorenzo@kalinga.com',
                'director_name'         => 'Dr. San Lorenzo Director',
                'capacity'              => 160,
                'bed_capacity'          => 160,
                'icu_capacity'          => 12,
                'negative_pressure_rooms' => 3,
                'level'                 => 'Level 2',
                'ownership'             => 'private',
                'type'                  => 'General',
                'latitude'              => 14.7369980,
                'longitude'             => 121.0691080,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => false,
                    'cold_storage'     => true,
                    'blood_bank'       => false,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Commonwealth Hospital and Medical Center',
                'code'                  => 'NCR-CHMC-001',
                'short_name'            => 'CHMC',
                'region'                => 'NCR',
                'province'              => 'Metro Manila',
                'city_municipality'     => 'Quezon City',
                'address'               => 'Regalado Hwy, Novaliches, Quezon City, Metro Manila',
                'phone'                 => '0288001018',
                'email'                 => 'chmc@kalinga.com',
                'director_name'         => 'Dr. CHMC Director',
                'capacity'              => 260,
                'bed_capacity'          => 260,
                'icu_capacity'          => 24,
                'negative_pressure_rooms' => 6,
                'level'                 => 'Level 2',
                'ownership'             => 'private',
                'type'                  => 'General',
                'latitude'              => 14.7326082,
                'longitude'             => 121.0608597,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
            [
                'name'                  => 'Amang Rodriguez Memorial Medical Center (ARMMC)',
                'code'                  => 'NCR-ARMMC-001',
                'short_name'            => 'ARMMC',
                'region'                => 'NCR',
                'province'              => 'Metro Manila',
                'city_municipality'     => 'Marikina City',
                'address'               => 'Sumulong Highway, Brgy. Santo Nino, Marikina City, Metro Manila',
                'phone'                 => '0288001011',
                'email'                 => 'armmc@kalinga.com',
                'director_name'         => 'Dr. ARMMC Director',
                'capacity'              => 450,
                'bed_capacity'          => 450,
                'icu_capacity'          => 48,
                'negative_pressure_rooms' => 12,
                'level'                 => 'Level 3',
                'ownership'             => 'government',
                'type'                  => 'General',
                'latitude'              => 14.6361803,
                'longitude'             => 121.0984460,
                'is_active'             => true,
                'is_cold_chain_capable' => true,
                'capabilities'          => [
                    'trauma_center'    => true,
                    'cold_storage'     => true,
                    'blood_bank'       => true,
                    'pharmacy_24hr'    => true,
                    'operating_theater'=> true,
                    'ambulance_bay'    => true,
                ],
            ],
        ];

        foreach ($hospitals as $hospital) {
            // Supabase PgBouncer can coerce PHP bool to integer; keep explicit boolean literals.
            $hospital['is_active'] = $hospital['is_active'] ? 'true' : 'false';
            $hospital['is_cold_chain_capable'] = $hospital['is_cold_chain_capable'] ? 'true' : 'false';
            Hospital::create($hospital);
        }
    }
}