<?php

namespace Database\Seeders;

use App\Models\PatientCareReport;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TempMockPCRSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function (): void {
            // Safe re-run: remove prior temporary mock PCR records first.
            PatientCareReport::query()
                ->where('case_no', 'LIKE', 'MOCK-TEMP%')
                ->delete();

            $now = Carbon::now();

            $records = [
                [
                    'report' => [
                        'user_id' => 39,
                        'incident_id' => null,
                        'patient_user_id' => null,
                        'case_no' => 'MOCK-TEMP-CAS-2026-3001',
                        'mobile_unit' => 'MOCK-TEMP-Ambulance 03',
                        'dispatch_date' => '2026-04-16',
                        'response_times' => [
                            'dispatchTime' => 'MOCK-TEMP-08:10:00',
                            'arrivalTime' => 'MOCK-TEMP-08:19:00',
                            'backToBaseTime' => 'MOCK-TEMP-09:42:00',
                        ],
                        'noi_moi' => ['MOCK-TEMP-Vehicular Crash', 'MOCK-TEMP-Trauma'],
                        'patient_details' => [
                            'name' => 'MOCK-TEMP-Ramon Dela Fuente',
                            'age' => 42,
                            'gender' => 'MOCK-TEMP-Male',
                            'address' => 'MOCK-TEMP-22 Mabini Street, Brgy. Burgos, Montalban',
                            'emergencyContact' => 'MOCK-TEMP-Lorna Dela Fuente 0917-555-0101',
                        ],
                        'physiological_status' => [
                            'levelOfConsciousness' => 'MOCK-TEMP-Pain',
                            'chiefComplaint' => 'MOCK-TEMP-Severe chest pain and right leg deformity after collision.',
                            'painLocation' => 'MOCK-TEMP-Chest and Right Lower Extremity',
                            'pmh' => ['MOCK-TEMP-Hypertension'],
                            'pmhOther' => 'MOCK-TEMP-No known allergies reported by bystander.',
                        ],
                        'vitals_entries' => [
                            [
                                'time' => 'MOCK-TEMP-08:21:00',
                                'bp' => '98/64',
                                'temp' => 36.4,
                                'rr' => 24,
                                'spo2' => 89,
                                'pulse' => 116,
                                'gcs' => ['eyes' => 2, 'verbal' => 3, 'motor' => 4],
                                'source' => 'manual',
                            ],
                            [
                                'time' => 'MOCK-TEMP-08:34:00',
                                'bp' => '94/60',
                                'temp' => 36.2,
                                'rr' => 26,
                                'spo2' => 86,
                                'pulse' => 122,
                                'gcs' => ['eyes' => 2, 'verbal' => 3, 'motor' => 4],
                                'source' => 'manual',
                            ],
                        ],
                        'gcs_entries' => [
                            ['time' => 'MOCK-TEMP-08:21:00', 'eyes' => 2, 'verbal' => 3, 'motor' => 4, 'total' => 9],
                            ['time' => 'MOCK-TEMP-08:34:00', 'eyes' => 2, 'verbal' => 3, 'motor' => 4, 'total' => 9],
                        ],
                        'management_transport' => [
                            'treatmentNarrative' => 'MOCK-TEMP-Cervical collar applied, oxygen via NRBM, right leg splinted.',
                            'transportedTo' => 'MOCK-TEMP-Amang Rodriguez Memorial Medical Center',
                            'admittingDoctor' => 'MOCK-TEMP-Dr. Esteban Santos',
                            'personnelOnScene' => 'MOCK-TEMP-Police and Traffic Enforcer',
                        ],
                        'waivers' => [
                            'consentForTreatment' => true,
                            'refusalOfTreatment' => false,
                            'equipmentLiabilityAgreement' => false,
                            'consentSignerName' => 'MOCK-TEMP-Lorna Dela Fuente',
                        ],
                        'edge_ingest_meta' => [
                            'source' => 'MOCK-TEMP-manual',
                            'sensor' => 'MOCK-TEMP-none',
                            'lastIngestedAt' => $now->copy()->subMinutes(3)->toIso8601String(),
                        ],
                        'soft_copy_path' => 'MOCK-TEMP-/storage/pcr/mock-temp-cas-2026-3001.pdf',
                        'status' => 'submitted',
                        'client_submission_id' => 'mock-temp-11111111-2222-4333-8444-000000000001',
                        'client_updated_at' => $now->copy()->subMinutes(2),
                        'submitted_at' => $now->copy()->subMinutes(2),
                    ],
                    'vitals' => [
                        [
                            'sort_order' => 0,
                            'recorded_time' => 'MOCK-TEMP-08:21:00',
                            'blood_pressure' => '98/64',
                            'temperature' => 36.4,
                            'respiratory_rate' => 24,
                            'spo2' => 89,
                            'pulse' => 116,
                            'gcs_eyes' => 2,
                            'gcs_verbal' => 3,
                            'gcs_motor' => 4,
                            'gcs_total' => 9,
                            'source' => 'manual',
                        ],
                        [
                            'sort_order' => 1,
                            'recorded_time' => 'MOCK-TEMP-08:34:00',
                            'blood_pressure' => '94/60',
                            'temperature' => 36.2,
                            'respiratory_rate' => 26,
                            'spo2' => 86,
                            'pulse' => 122,
                            'gcs_eyes' => 2,
                            'gcs_verbal' => 3,
                            'gcs_motor' => 4,
                            'gcs_total' => 9,
                            'source' => 'manual',
                        ],
                    ],
                    'waiver' => [
                        'consent_for_treatment' => true,
                        'refusal_of_treatment' => false,
                        'equipment_liability_agreement' => false,
                        'signer_name' => 'MOCK-TEMP-Lorna Dela Fuente',
                        'consent_signature_path' => 'MOCK-TEMP-data:image/png;base64,consent-3001',
                        'refusal_signature_path' => null,
                        'equipment_signature_path' => null,
                    ],
                ],
                [
                    'report' => [
                        'user_id' => 39,
                        'incident_id' => null,
                        'patient_user_id' => null,
                        'case_no' => 'MOCK-TEMP-CAS-2026-3002',
                        'mobile_unit' => 'MOCK-TEMP-Ambulance 01',
                        'dispatch_date' => '2026-04-16',
                        'response_times' => [
                            'dispatchTime' => 'MOCK-TEMP-10:02:00',
                            'arrivalTime' => 'MOCK-TEMP-10:11:00',
                            'backToBaseTime' => 'MOCK-TEMP-10:58:00',
                        ],
                        'noi_moi' => ['MOCK-TEMP-Respiratory Distress'],
                        'patient_details' => [
                            'name' => 'MOCK-TEMP-Elena Villareal',
                            'age' => 24,
                            'gender' => 'MOCK-TEMP-Female',
                            'address' => 'MOCK-TEMP-Phase 2 Eastwood Greenview, Montalban',
                            'emergencyContact' => 'MOCK-TEMP-Roberto Villareal 0998-555-0102',
                        ],
                        'physiological_status' => [
                            'levelOfConsciousness' => 'MOCK-TEMP-Alert',
                            'chiefComplaint' => 'MOCK-TEMP-Wheezing and progressive shortness of breath.',
                            'painLocation' => 'MOCK-TEMP-Chest',
                            'pmh' => ['MOCK-TEMP-Asthma', 'MOCK-TEMP-Allergies'],
                            'pmhOther' => 'MOCK-TEMP-Uses inhaler as needed.',
                        ],
                        'vitals_entries' => [
                            [
                                'time' => 'MOCK-TEMP-10:14:00',
                                'bp' => '116/74',
                                'temp' => 37.0,
                                'rr' => 23,
                                'spo2' => 91,
                                'pulse' => 101,
                                'gcs' => ['eyes' => 4, 'verbal' => 5, 'motor' => 6],
                                'source' => 'manual',
                            ],
                            [
                                'time' => 'MOCK-TEMP-10:25:00',
                                'bp' => '112/72',
                                'temp' => 36.9,
                                'rr' => 19,
                                'spo2' => 97,
                                'pulse' => 88,
                                'gcs' => ['eyes' => 4, 'verbal' => 5, 'motor' => 6],
                                'source' => 'manual',
                            ],
                        ],
                        'gcs_entries' => [
                            ['time' => 'MOCK-TEMP-10:14:00', 'eyes' => 4, 'verbal' => 5, 'motor' => 6, 'total' => 15],
                            ['time' => 'MOCK-TEMP-10:25:00', 'eyes' => 4, 'verbal' => 5, 'motor' => 6, 'total' => 15],
                        ],
                        'management_transport' => [
                            'treatmentNarrative' => 'MOCK-TEMP-Nebulization started, patient improved and refused transport.',
                            'transportedTo' => 'MOCK-TEMP-Scene to Home (Refused Transport)',
                            'admittingDoctor' => 'MOCK-TEMP-N/A',
                            'personnelOnScene' => 'MOCK-TEMP-Relative',
                        ],
                        'waivers' => [
                            'consentForTreatment' => true,
                            'refusalOfTreatment' => true,
                            'equipmentLiabilityAgreement' => false,
                            'consentSignerName' => 'MOCK-TEMP-Elena Villareal',
                        ],
                        'edge_ingest_meta' => [
                            'source' => 'MOCK-TEMP-manual',
                            'sensor' => 'MOCK-TEMP-none',
                            'lastIngestedAt' => $now->copy()->subMinutes(25)->toIso8601String(),
                        ],
                        'soft_copy_path' => 'MOCK-TEMP-/storage/pcr/mock-temp-cas-2026-3002.pdf',
                        'status' => 'submitted',
                        'client_submission_id' => 'mock-temp-11111111-2222-4333-8444-000000000002',
                        'client_updated_at' => $now->copy()->subMinutes(20),
                        'submitted_at' => $now->copy()->subMinutes(20),
                    ],
                    'vitals' => [
                        [
                            'sort_order' => 0,
                            'recorded_time' => 'MOCK-TEMP-10:14:00',
                            'blood_pressure' => '116/74',
                            'temperature' => 37.0,
                            'respiratory_rate' => 23,
                            'spo2' => 91,
                            'pulse' => 101,
                            'gcs_eyes' => 4,
                            'gcs_verbal' => 5,
                            'gcs_motor' => 6,
                            'gcs_total' => 15,
                            'source' => 'manual',
                        ],
                        [
                            'sort_order' => 1,
                            'recorded_time' => 'MOCK-TEMP-10:25:00',
                            'blood_pressure' => '112/72',
                            'temperature' => 36.9,
                            'respiratory_rate' => 19,
                            'spo2' => 97,
                            'pulse' => 88,
                            'gcs_eyes' => 4,
                            'gcs_verbal' => 5,
                            'gcs_motor' => 6,
                            'gcs_total' => 15,
                            'source' => 'manual',
                        ],
                    ],
                    'waiver' => [
                        'consent_for_treatment' => true,
                        'refusal_of_treatment' => true,
                        'equipment_liability_agreement' => false,
                        'signer_name' => 'MOCK-TEMP-Elena Villareal',
                        'consent_signature_path' => 'MOCK-TEMP-data:image/png;base64,consent-3002',
                        'refusal_signature_path' => 'MOCK-TEMP-data:image/png;base64,refusal-3002',
                        'equipment_signature_path' => null,
                    ],
                ],
                [
                    'report' => [
                        'user_id' => 39,
                        'incident_id' => null,
                        'patient_user_id' => null,
                        'case_no' => 'MOCK-TEMP-CAS-2026-3003',
                        'mobile_unit' => 'MOCK-TEMP-Ambulance 02',
                        'dispatch_date' => '2026-04-15',
                        'response_times' => [
                            'dispatchTime' => 'MOCK-TEMP-23:05:00',
                            'arrivalTime' => 'MOCK-TEMP-23:13:00',
                            'backToBaseTime' => 'MOCK-TEMP-00:21:00',
                        ],
                        'noi_moi' => ['MOCK-TEMP-Fall', 'MOCK-TEMP-Head Injury'],
                        'patient_details' => [
                            'name' => 'MOCK-TEMP-Unknown Male Worker',
                            'age' => 35,
                            'gender' => 'MOCK-TEMP-Male',
                            'address' => 'MOCK-TEMP-Construction Site Brgy. San Jose, Montalban',
                            'emergencyContact' => 'MOCK-TEMP-None available on scene',
                        ],
                        'physiological_status' => [
                            'levelOfConsciousness' => 'MOCK-TEMP-Unconscious',
                            'chiefComplaint' => 'MOCK-TEMP-Fall from scaffolding with altered mental status.',
                            'painLocation' => 'MOCK-TEMP-Head and Left Shoulder',
                            'pmh' => ['MOCK-TEMP-Unknown'],
                            'pmhOther' => 'MOCK-TEMP-History unavailable at scene.',
                        ],
                        'vitals_entries' => [
                            [
                                'time' => 'MOCK-TEMP-23:16:00',
                                'bp' => '146/94',
                                'temp' => 36.7,
                                'rr' => 12,
                                'spo2' => 90,
                                'pulse' => 64,
                                'gcs' => ['eyes' => 1, 'verbal' => 2, 'motor' => 4],
                                'source' => 'manual',
                            ],
                        ],
                        'gcs_entries' => [
                            ['time' => 'MOCK-TEMP-23:16:00', 'eyes' => 1, 'verbal' => 2, 'motor' => 4, 'total' => 7],
                        ],
                        'management_transport' => [
                            'treatmentNarrative' => 'MOCK-TEMP-C-spine immobilization and assisted ventilation initiated.',
                            'transportedTo' => 'MOCK-TEMP-Rizal Provincial Hospital',
                            'admittingDoctor' => 'MOCK-TEMP-Dr. M. Alonzo',
                            'personnelOnScene' => 'MOCK-TEMP-Bystanders and Site Supervisor',
                        ],
                        'waivers' => [
                            'consentForTreatment' => false,
                            'refusalOfTreatment' => false,
                            'equipmentLiabilityAgreement' => false,
                            'consentSignerName' => 'MOCK-TEMP-N/A',
                        ],
                        'edge_ingest_meta' => [
                            'source' => 'MOCK-TEMP-manual',
                            'sensor' => 'MOCK-TEMP-none',
                            'lastIngestedAt' => $now->copy()->subDay()->toIso8601String(),
                        ],
                        'soft_copy_path' => null,
                        'status' => 'draft',
                        'client_submission_id' => 'mock-temp-11111111-2222-4333-8444-000000000003',
                        'client_updated_at' => $now->copy()->subDay(),
                        'submitted_at' => null,
                    ],
                    'vitals' => [
                        [
                            'sort_order' => 0,
                            'recorded_time' => 'MOCK-TEMP-23:16:00',
                            'blood_pressure' => '146/94',
                            'temperature' => 36.7,
                            'respiratory_rate' => 12,
                            'spo2' => 90,
                            'pulse' => 64,
                            'gcs_eyes' => 1,
                            'gcs_verbal' => 2,
                            'gcs_motor' => 4,
                            'gcs_total' => 7,
                            'source' => 'manual',
                        ],
                    ],
                    'waiver' => [
                        'consent_for_treatment' => false,
                        'refusal_of_treatment' => false,
                        'equipment_liability_agreement' => false,
                        'signer_name' => 'MOCK-TEMP-N/A',
                        'consent_signature_path' => null,
                        'refusal_signature_path' => null,
                        'equipment_signature_path' => null,
                    ],
                ],
                [
                    'report' => [
                        'user_id' => 39,
                        'incident_id' => null,
                        'patient_user_id' => null,
                        'case_no' => 'MOCK-TEMP-CAS-2026-3004',
                        'mobile_unit' => 'MOCK-TEMP-Ambulance 04',
                        'dispatch_date' => '2026-04-15',
                        'response_times' => [
                            'dispatchTime' => 'MOCK-TEMP-14:40:00',
                            'arrivalTime' => 'MOCK-TEMP-14:49:00',
                            'backToBaseTime' => 'MOCK-TEMP-15:35:00',
                        ],
                        'noi_moi' => ['MOCK-TEMP-Seizure'],
                        'patient_details' => [
                            'name' => 'MOCK-TEMP-Jonathan Cruz',
                            'age' => 19,
                            'gender' => 'MOCK-TEMP-Male',
                            'address' => 'MOCK-TEMP-Sitio Riverside Brgy. Puray, Montalban',
                            'emergencyContact' => 'MOCK-TEMP-Gloria Cruz 0917-555-0104',
                        ],
                        'physiological_status' => [
                            'levelOfConsciousness' => 'MOCK-TEMP-Verbal',
                            'chiefComplaint' => 'MOCK-TEMP-Generalized seizure lasting approximately 3 minutes.',
                            'painLocation' => 'MOCK-TEMP-None reported post-ictal',
                            'pmh' => ['MOCK-TEMP-Seizure'],
                            'pmhOther' => 'MOCK-TEMP-Missed maintenance medication this morning.',
                        ],
                        'vitals_entries' => [
                            [
                                'time' => 'MOCK-TEMP-14:52:00',
                                'bp' => '124/80',
                                'temp' => 36.8,
                                'rr' => 20,
                                'spo2' => 95,
                                'pulse' => 98,
                                'gcs' => ['eyes' => 3, 'verbal' => 4, 'motor' => 6],
                                'source' => 'manual',
                            ],
                            [
                                'time' => 'MOCK-TEMP-15:10:00',
                                'bp' => '120/78',
                                'temp' => 36.9,
                                'rr' => 18,
                                'spo2' => 97,
                                'pulse' => 90,
                                'gcs' => ['eyes' => 4, 'verbal' => 5, 'motor' => 6],
                                'source' => 'manual',
                            ],
                        ],
                        'gcs_entries' => [
                            ['time' => 'MOCK-TEMP-14:52:00', 'eyes' => 3, 'verbal' => 4, 'motor' => 6, 'total' => 13],
                            ['time' => 'MOCK-TEMP-15:10:00', 'eyes' => 4, 'verbal' => 5, 'motor' => 6, 'total' => 15],
                        ],
                        'management_transport' => [
                            'treatmentNarrative' => 'MOCK-TEMP-Airway monitored, lateral position maintained, oxygen support provided.',
                            'transportedTo' => 'MOCK-TEMP-Montalban Infirmary',
                            'admittingDoctor' => 'MOCK-TEMP-Dr. Karen Uy',
                            'personnelOnScene' => 'MOCK-TEMP-Relative',
                        ],
                        'waivers' => [
                            'consentForTreatment' => true,
                            'refusalOfTreatment' => false,
                            'equipmentLiabilityAgreement' => false,
                            'consentSignerName' => 'MOCK-TEMP-Gloria Cruz',
                        ],
                        'edge_ingest_meta' => [
                            'source' => 'MOCK-TEMP-manual',
                            'sensor' => 'MOCK-TEMP-none',
                            'lastIngestedAt' => $now->copy()->subHours(14)->toIso8601String(),
                        ],
                        'soft_copy_path' => 'MOCK-TEMP-/storage/pcr/mock-temp-cas-2026-3004.pdf',
                        'status' => 'submitted',
                        'client_submission_id' => 'mock-temp-11111111-2222-4333-8444-000000000004',
                        'client_updated_at' => $now->copy()->subHours(13),
                        'submitted_at' => $now->copy()->subHours(13),
                    ],
                    'vitals' => [
                        [
                            'sort_order' => 0,
                            'recorded_time' => 'MOCK-TEMP-14:52:00',
                            'blood_pressure' => '124/80',
                            'temperature' => 36.8,
                            'respiratory_rate' => 20,
                            'spo2' => 95,
                            'pulse' => 98,
                            'gcs_eyes' => 3,
                            'gcs_verbal' => 4,
                            'gcs_motor' => 6,
                            'gcs_total' => 13,
                            'source' => 'manual',
                        ],
                        [
                            'sort_order' => 1,
                            'recorded_time' => 'MOCK-TEMP-15:10:00',
                            'blood_pressure' => '120/78',
                            'temperature' => 36.9,
                            'respiratory_rate' => 18,
                            'spo2' => 97,
                            'pulse' => 90,
                            'gcs_eyes' => 4,
                            'gcs_verbal' => 5,
                            'gcs_motor' => 6,
                            'gcs_total' => 15,
                            'source' => 'manual',
                        ],
                    ],
                    'waiver' => [
                        'consent_for_treatment' => true,
                        'refusal_of_treatment' => false,
                        'equipment_liability_agreement' => false,
                        'signer_name' => 'MOCK-TEMP-Gloria Cruz',
                        'consent_signature_path' => 'MOCK-TEMP-data:image/png;base64,consent-3004',
                        'refusal_signature_path' => null,
                        'equipment_signature_path' => null,
                    ],
                ],
                [
                    'report' => [
                        'user_id' => 39,
                        'incident_id' => null,
                        'patient_user_id' => null,
                        'case_no' => 'MOCK-TEMP-CAS-2026-3005',
                        'mobile_unit' => 'MOCK-TEMP-Rescue Van 05',
                        'dispatch_date' => '2026-04-14',
                        'response_times' => [
                            'dispatchTime' => 'MOCK-TEMP-19:12:00',
                            'arrivalTime' => 'MOCK-TEMP-19:23:00',
                            'backToBaseTime' => 'MOCK-TEMP-20:05:00',
                        ],
                        'noi_moi' => ['MOCK-TEMP-Burn Injury'],
                        'patient_details' => [
                            'name' => 'MOCK-TEMP-Maria Estrella',
                            'age' => 56,
                            'gender' => 'MOCK-TEMP-Female',
                            'address' => 'MOCK-TEMP-Purok 5 Brgy. Rosario, Montalban',
                            'emergencyContact' => 'MOCK-TEMP-Edgar Estrella 0918-555-0105',
                        ],
                        'physiological_status' => [
                            'levelOfConsciousness' => 'MOCK-TEMP-Alert',
                            'chiefComplaint' => 'MOCK-TEMP-Partial thickness burns on left forearm from kitchen fire.',
                            'painLocation' => 'MOCK-TEMP-Left Forearm and Dorsal Hand',
                            'pmh' => ['MOCK-TEMP-Diabetic'],
                            'pmhOther' => 'MOCK-TEMP-On oral hypoglycemic medication.',
                        ],
                        'vitals_entries' => [
                            [
                                'time' => 'MOCK-TEMP-19:27:00',
                                'bp' => '136/84',
                                'temp' => 37.2,
                                'rr' => 21,
                                'spo2' => 98,
                                'pulse' => 94,
                                'gcs' => ['eyes' => 4, 'verbal' => 5, 'motor' => 6],
                                'source' => 'manual',
                            ],
                        ],
                        'gcs_entries' => [
                            ['time' => 'MOCK-TEMP-19:27:00', 'eyes' => 4, 'verbal' => 5, 'motor' => 6, 'total' => 15],
                        ],
                        'management_transport' => [
                            'treatmentNarrative' => 'MOCK-TEMP-Cool water irrigation and sterile dressing applied.',
                            'transportedTo' => 'MOCK-TEMP-Casimiro Ynares Sr. Memorial Hospital',
                            'admittingDoctor' => 'MOCK-TEMP-Dr. Bea Navarro',
                            'personnelOnScene' => 'MOCK-TEMP-Relative and Neighbor',
                        ],
                        'waivers' => [
                            'consentForTreatment' => true,
                            'refusalOfTreatment' => false,
                            'equipmentLiabilityAgreement' => true,
                            'consentSignerName' => 'MOCK-TEMP-Maria Estrella',
                        ],
                        'edge_ingest_meta' => [
                            'source' => 'MOCK-TEMP-manual',
                            'sensor' => 'MOCK-TEMP-none',
                            'lastIngestedAt' => $now->copy()->subDays(2)->toIso8601String(),
                        ],
                        'soft_copy_path' => 'MOCK-TEMP-/storage/pcr/mock-temp-cas-2026-3005.pdf',
                        'status' => 'submitted',
                        'client_submission_id' => 'mock-temp-11111111-2222-4333-8444-000000000005',
                        'client_updated_at' => $now->copy()->subDays(2),
                        'submitted_at' => $now->copy()->subDays(2),
                    ],
                    'vitals' => [
                        [
                            'sort_order' => 0,
                            'recorded_time' => 'MOCK-TEMP-19:27:00',
                            'blood_pressure' => '136/84',
                            'temperature' => 37.2,
                            'respiratory_rate' => 21,
                            'spo2' => 98,
                            'pulse' => 94,
                            'gcs_eyes' => 4,
                            'gcs_verbal' => 5,
                            'gcs_motor' => 6,
                            'gcs_total' => 15,
                            'source' => 'manual',
                        ],
                    ],
                    'waiver' => [
                        'consent_for_treatment' => true,
                        'refusal_of_treatment' => false,
                        'equipment_liability_agreement' => true,
                        'signer_name' => 'MOCK-TEMP-Maria Estrella',
                        'consent_signature_path' => 'MOCK-TEMP-data:image/png;base64,consent-3005',
                        'refusal_signature_path' => null,
                        'equipment_signature_path' => 'MOCK-TEMP-data:image/png;base64,equipment-3005',
                    ],
                ],
            ];

            foreach ($records as $record) {
                $report = PatientCareReport::create($record['report']);
                $report->vitals()->createMany($record['vitals']);
                $report->waiver()->create($record['waiver']);
            }
        });
    }
}
